export const GET_PRODUCTS = 'GET_PRODUCTS'
export const ADD_TO_ORDER = 'ADD_TO_ORDER'
export const REMOVE_TO_ORDER = 'REMOVE_TO_ORDER'

export const AUTHENTICATED = 'AUTHENTICATED'
export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED'